version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5492:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MailDev
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1080:1080"  # MailDev UI
      - "1025:1025"  # SMTP

  # Laravel Backend
  backend:
    build:
      context: ./task-manager-api
    container_name: laravel-backend
    depends_on:
      - postgres
      - maildev
    volumes:
      - ./task-manager-api:/var/www
    ports:
      - "8000:8000"
    command: >
      sh -c "php artisan config:clear &&
             php artisan migrate:fresh --seed &&
             php artisan serve --host=0.0.0.0 --port=8000"

  # Vue Vite Frontend
  frontend:
    build:
      context: ./task-manager
    container_name: vite-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./task-manager:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - VITE_BACKEND_URL=http://localhost:8000/api

volumes:
  pgdata:
